language: node_js

node_js:
  - lts/*
  -
branches:
  except:
    - gh-pages

after_success:
  - npm run coverage:coveralls
  - ./gendoc.sh

env:
  gloval:
    secure: "d4lCLgBmD5RTtom7+52EsKnQ5VAuqG03OynOFgLjZtYHTZDrXtwchpBrwcDUjBZhFxH5tK8gy3B7ekFkVh9hA649o0J7l+Coztx5gUbSx5yExDgv4ILG1lo316MVpyViZPxPVDfXbA+JKX4JGlmgaAwyxYxvyKdcp1SY6a4WLWr5jpB+WNkjYPX1DedUgOLa2KZBqmt6QjcqIKAiez8iqbL72B8XmAvYJTTbQXrM7bVOchkFY+kmXnKwv0agfUhmP7NxGF4Zdmn0Y6C1PmrvVW6qiGM5IjHrqOWjRN4zxLpyGlVoWLvW0ceWKeHBT1F1ZqVN46OQkHIc1qhIfQ2q/84mCyl14qnoUSaauYJHHUI5FCd6oYMhNZzyMQjt2o0n/XkceINKfZ7IJJIIKue6lcmVjmSjirft9ITyfNxnJSsesP8bvw+Lxgkqcv5t6+j2htUPmz4xl5tw64GIqtzxRXpIMXKTFRcd2q7TCRrXr3MTRryHLx5TCjNzRrAug2Bfnw7MATofifgIDCW5PrODnAlPV6XX1pyt36sl03zdZ7Hja6zL9wZa5sGs0TWMGKxZAmGoOnnFs+fztSArbJ0dVDS76xfegCH40yLyQZ/GpE6Eljsq6ortQ32LKgqTRI5R7qKLdNMC98TNoCJUuMEEpAGu03QEiGrlvi99lW5X4+U="
